# Where should we write the GIF?
Output ./vhs/demo.gif

Set Margin 20
Set MarginFill "#ffffff"
Set BorderRadius 10

# Set up a 1200x600 terminal with 46px font.
Set FontSize 20
Set Width 1200
Set Height 600

# Type a command in the terminal.
Type "openai chat"

# Pause for dramatic effect.
Sleep 500ms

# Run the command by pressing enter.
Enter

# Pause for dramatic effect.
Sleep 500ms

# Type a command in the terminal.
Type "system: You are Jarvis, a helpful assistant."

# Pause for dramatic effect.
Sleep 500ms

# Run the command by pressing enter.
Enter

# Type a command in the terminal.
Type "Hello Jarvis, what is your name?"

# Pause for dramatic effect.
Sleep 500ms

# Run the command by pressing enter.
Enter

# Wait for the command to finish.
Sleep 2s

# Type a command in the terminal.
Type "er"

# Tab complete the command.
Tab@500ms 2

# Pause for dramatic effect.
Sleep 500ms

# Run the command by pressing enter.
Enter

# Type a command in the terminal.
Type "ex"

# Tab complete the command.
Tab@500ms 2

# Run the command by pressing enter.
Enter

# Admire the output for a bit.
Sleep 5s
