# Where should we write the GIF?
Output ./vhs/demo.gif

Set Margin 20
Set MarginFill "#ffffff"
Set BorderRadius 10

# Set up a 1200x600 terminal with 46px font.
Set FontSize 20
Set Width 1200
Set Height 600

# Type a command in the terminal.
Type "openai assistant"

# Pause for dramatic effect.
Sleep 500ms

# Run the command by pressing enter.
Enter

# Pause for dramatic effect.
Sleep 500ms

# Pause for dramatic effect.
Sleep 500ms

# Type a command in the terminal.
Type "Hello!"

# Pause for dramatic effect.
Sleep 500ms

# Run the command by pressing enter.
Enter

# Wait for the command to finish.
Sleep 2s

# Type a command in the terminal.
Type "speak!"

# Pause for dramatic effect.
Sleep 500ms

# Run the command by pressing enter.
Enter

# Wait for the command to finish.
Sleep 1s

# Type a command in the terminal.
Type "What is software engineering? Be as concise as possible."

# Pause for dramatic effect.
Sleep 500ms

# Run the command by pressing enter.
Enter

# Wait for the command to finish.
Sleep 20s

# Type a command in the terminal.
Type "upload /tmp/attention-is-all-you-need.pdf"

# Pause for dramatic effect.
Sleep 500ms

# Run the command by pressing enter.
Enter

# Wait for the command to finish.
Sleep 4s

# Type a command in the terminal.
Type "ls"

# Pause for dramatic effect.
Sleep 500ms

# Run the command by pressing enter.
Enter

# Wait for the command to finish.
Sleep 4s

# Type a command in the terminal.
Type "In the PDF I just uploaded, who is the first author listed?"

# Pause for dramatic effect.
Sleep 500ms

# Run the command by pressing enter.
Enter

# Wait for the command to finish.
Sleep 20s

# Type a command in the terminal.
Type "ex"

# Tab complete the command.
Tab@500ms 2

# Pause for dramatic effect.
Sleep 500ms

# Run the command by pressing enter.
Enter

# Admire the output for a bit.
Sleep 5s
